export const fontFamily = {
    thin: "Poppins_100Thin",
    thin_italic: "Poppins_100Thin_Italic",
    extra_light: "Poppins_200ExtraLight",
    extra_light_italic: "Poppins_200ExtraLight_Italic",
    light: "Poppins_300Light",
    light_italic: "Poppins_300Light_Italic",
    regular: "Poppins_400Regular",
    regular_italic: "Poppins_400Regular_Italic",
    medium: "Poppins_500Medium",
    medium_italic: "Poppins_500Medium_Italic",
    semi_bold: "Poppins_600SemiBold",
    semi_bold_italic: "Poppins_600SemiBold_Italic",
    bold: "Poppins_700Bold",
    bold_italic: "Poppins_700Bold_Italic",
    extra_bold: "Poppins_800ExtraBold",
    extra_bold_italic: "Poppins_800ExtraBold_Italic",
    black: "Poppins_900Black",
    black_italic: "Poppins_900Black_Italic",
};